# Generated by Django 4.1.5 on 2023-01-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("Phonenumber", models.IntegerField()),
                ("age", models.IntegerField()),
                ("occupation", models.CharField(max_length=250)),
                ("gender", models.CharField(max_length=250)),
                ("medium", models.CharField(max_length=250)),
                ("problem", models.CharField(max_length=250)),
                ("easy", models.CharField(max_length=250)),
                ("price", models.CharField(max_length=250)),
                ("comparison", models.CharField(max_length=250)),
            ],
        ),
    ]
