# Generated by Django 4.1.5 on 2023-01-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey", name="Phonenumber", field=models.BigIntegerField(),
        ),
    ]
