# Generated by Django 4.1.5 on 2023-01-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0002_alter_survey_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="survey2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("Have_smartphone", models.CharField(max_length=250)),
                ("which_phone", models.CharField(max_length=250)),
                ("factors_influence", models.CharField(max_length=250)),
                ("rating_own_phone", models.IntegerField()),
                ("describe_your_phone", models.CharField(max_length=250)),
                ("Mojor_concern", models.CharField(max_length=250)),
                ("apps_security", models.IntegerField()),
                ("ios_android", models.CharField(max_length=250)),
                ("occupation", models.CharField(max_length=250)),
            ],
        ),
    ]
