# Generated by Django 4.1.5 on 2023-01-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0003_survey2"),
    ]

    operations = [
        migrations.RenameModel(old_name="survey2", new_name="surveyB",),
    ]
