# Generated by Django 4.1.5 on 2023-01-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0004_rename_survey2_surveyb"),
    ]

    operations = [
        migrations.CreateModel(
            name="report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("comment", models.TextField()),
            ],
        ),
    ]
